export const laminations = [
  { label: 'None', value: 'none' },
  { label: 'Gloss', value: 'gloss' },
  { label: 'Thermal Gloss', value: 'thermal_gloss' },
  { label: 'Wet Gloss', value: 'wet_gloss' },
  { label: 'Matte', value: 'matte' },
  { label: 'Thermal Matte', value: 'thermal_matte' },
  { label: 'Wet Matte', value: 'wet_matte' },
  { label: 'Velvet', value: 'velvet' },
  { label: 'Thermal Velvet', value: 'thermal_velvet' },
  { label: 'Wet Velvet', value: 'wet_velvet' },
  { label: 'Metallic', value: 'metallic' },
  { label: 'Thermal Metallic', value: 'thermal_metallic' },
  { label: 'Wet Metallic', value: 'wet_metallic' },
  { label: 'Silk', value: 'silk' },
  { label: 'Thermal Silk', value: 'thermal_silk' },
  { label: 'Wet Silk', value: 'wet_silk' },
  { label: 'Soft Touch', value: 'soft_touch' },
  { label: 'Thermal Soft Touch', value: 'thermal_soft_touch' },
  { label: 'Wet Soft Touch', value: 'wet_soft_touch' },
  { label: 'Anti-Scratch', value: 'anti_scratch' },
  { label: 'Thermal Anti-Scratch', value: 'thermal_anti_scratch' },
  { label: 'Wet Anti-Scratch', value: 'wet_anti_scratch' },
  { label: 'Textured', value: 'textured' },
  { label: 'Thermal Textured', value: 'thermal_textured' },
  { label: 'Wet Textured', value: 'wet_textured' },
  { label: 'UV', value: 'uv' },
  { label: 'Thermal UV', value: 'thermal_uv' },
  { label: 'Wet UV', value: 'wet_uv' },
  { label: 'Digital', value: 'digital' },
  { label: 'Thermal Digital', value: 'thermal_digital' },
  { label: 'Wet Digital', value: 'wet_digital' },
]

export const commonSizes = [
  { label: 'A0', length: 1189, width: 841 },
  { label: 'A1', length: 841, width: 594 },
  { label: 'A2', length: 594, width: 420 },
  { label: 'A3', length: 420, width: 297 },
  { label: 'A4', length: 297, width: 210 },
  { label: 'A5', length: 210, width: 148 },
  { label: 'A6', length: 148, width: 105 },
  { label: 'A7', length: 105, width: 74 },
  { label: 'A8', length: 74, width: 52 },
  { label: 'A9', length: 52, width: 37 },
  { label: 'A10', length: 37, width: 26 },
  { label: 'B0', length: 1414, width: 1000 },
  { label: 'B1', length: 1000, width: 707 },
  { label: 'B2', length: 707, width: 500 },
  { label: 'B3', length: 500, width: 353 },
  { label: 'B4', length: 353, width: 250 },
  { label: 'B5', length: 250, width: 176 },
  { label: 'B6', length: 176, width: 125 },
  { label: 'B7', length: 125, width: 88 },
  { label: 'B8', length: 88, width: 62 },
  { label: 'B9', length: 62, width: 44 },
  { label: 'B10', length: 44, width: 31 },
  { label: 'C0', length: 1297, width: 917 },
  { label: 'C1', length: 917, width: 648 },
  { label: 'C2', length: 648, width: 458 },
  { label: 'C3', length: 458, width: 324 },
  { label: 'C4', length: 324, width: 229 },
  { label: 'C5', length: 229, width: 162 },
  { label: 'C6', length: 162, width: 114 },
  { label: 'C7', length: 114, width: 81 },
  { label: 'C8', length: 81, width: 57 },
  { label: 'C9', length: 57, width: 40 },
  { label: 'C10', length: 40, width: 28 },
  { label: 'Letter', length: 279.4, width: 215.9 },
  { label: 'Legal', length: 355.6, width: 215.9 },
  { label: 'Tabloid', length: 431.8, width: 279.4 },
  { label: 'Ledger', length: 279.4, width: 431.8 },
  { label: 'Executive', length: 266.7, width: 184.1 },
  { label: 'Folio', length: 330.2, width: 215.9 },
  { label: 'Quarto', length: 254, width: 203.2 },
  { label: 'Postcard', length: 148, width: 105 },
  { label: 'Index Card', length: 127, width: 76.2 },
  { label: 'Custom', length: 0, width: 0 },
]
