export const laminations = [
  { label: 'None', value: 'none' },
  { label: 'Gloss', value: 'gloss' },
  { label: 'Thermal Gloss', value: 'thermal_gloss' },
  { label: 'Wet Gloss', value: 'wet_gloss' },
  { label: 'Matte', value: 'matte' },
  { label: 'Thermal Matte', value: 'thermal_matte' },
  { label: 'Wet Matte', value: 'wet_matte' },
  { label: 'Velvet', value: 'velvet' },
  { label: 'Thermal Velvet', value: 'thermal_velvet' },
  { label: 'Wet Velvet', value: 'wet_velvet' },
  { label: 'Metallic', value: 'metallic' },
  { label: 'Thermal Metallic', value: 'thermal_metallic' },
  { label: 'Wet Metallic', value: 'wet_metallic' },
  { label: 'Silk', value: 'silk' },
  { label: 'Thermal Silk', value: 'thermal_silk' },
  { label: 'Wet Silk', value: 'wet_silk' },
  { label: 'Soft Touch', value: 'soft_touch' },
  { label: 'Thermal Soft Touch', value: 'thermal_soft_touch' },
  { label: 'Wet Soft Touch', value: 'wet_soft_touch' },
  { label: 'Anti-Scratch', value: 'anti_scratch' },
  { label: 'Thermal Anti-Scratch', value: 'thermal_anti_scratch' },
  { label: 'Wet Anti-Scratch', value: 'wet_anti_scratch' },
  { label: 'Textured', value: 'textured' },
  { label: 'Thermal Textured', value: 'thermal_textured' },
  { label: 'Wet Textured', value: 'wet_textured' },
  { label: 'UV', value: 'uv' },
  { label: 'Thermal UV', value: 'thermal_uv' },
  { label: 'Wet UV', value: 'wet_uv' },
  { label: 'Digital', value: 'digital' },
  { label: 'Thermal Digital', value: 'thermal_digital' },
  { label: 'Wet Digital', value: 'wet_digital' },
]

export const commonSizes = [
  { label: 'A0 Portrait', length: 1189, width: 841 },
  { label: 'A0 Landscape', length: 841, width: 1189 },
  { label: 'A1 Portrait', length: 841, width: 594 },
  { label: 'A1 Landscape', length: 594, width: 841 },
  { label: 'A2 Portrait', length: 594, width: 420 },
  { label: 'A2 Landscape', length: 420, width: 594 },
  { label: 'A3 Portrait', length: 420, width: 297 },
  { label: 'A3 Landscape', length: 297, width: 420 },
  { label: 'A4 Portrait', length: 297, width: 210 },
  { label: 'A4 Landscape', length: 210, width: 297 },
  { label: 'A5 Portrait', length: 210, width: 148 },
  { label: 'A5 Landscape', length: 148, width: 210 },
  { label: 'A6 Portrait', length: 148, width: 105 },
  { label: 'A6 Landscape', length: 105, width: 148 },
  { label: 'A7 Portrait', length: 105, width: 74 },
  { label: 'A7 Landscape', length: 74, width: 105 },
  { label: 'A8 Portrait', length: 74, width: 52 },
  { label: 'A8 Landscape', length: 52, width: 74 },
  { label: 'A9 Portrait', length: 52, width: 37 },
  { label: 'A9 Landscape', length: 37, width: 52 },
  { label: 'A10 Portrait', length: 37, width: 26 },
  { label: 'A10 Landscape', length: 26, width: 37 },
  { label: 'B0 Portrait', length: 1414, width: 1000 },
  { label: 'B0 Landscape', length: 1000, width: 1414 },
  { label: 'B1 Portrait', length: 1000, width: 707 },
  { label: 'B1 Landscape', length: 707, width: 1000 },
  { label: 'B2 Portrait', length: 707, width: 500 },
  { label: 'B2 Landscape', length: 500, width: 707 },
  { label: 'B3 Portrait', length: 500, width: 353 },
  { label: 'B3 Landscape', length: 353, width: 500 },
  { label: 'B4 Portrait', length: 353, width: 250 },
  { label: 'B4 Landscape', length: 250, width: 353 },
  { label: 'B5 Portrait', length: 250, width: 176 },
  { label: 'B5 Landscape', length: 176, width: 250 },
  { label: 'B6 Portrait', length: 176, width: 125 },
  { label: 'B6 Landscape', length: 125, width: 176 },
  { label: 'B7 Portrait', length: 125, width: 88 },
  { label: 'B7 Landscape', length: 88, width: 125 },
  { label: 'B8 Portrait', length: 88, width: 62 },
  { label: 'B8 Landscape', length: 62, width: 88 },
  { label: 'B9 Portrait', length: 62, width: 44 },
  { label: 'B9 Landscape', length: 44, width: 62 },
  { label: 'B10 Portrait', length: 44, width: 31 },
  { label: 'B10 Landscape', length: 31, width: 44 },
  { label: 'C0 Portrait', length: 1297, width: 917 },
  { label: 'C0 Landscape', length: 917, width: 1297 },
  { label: 'C1 Portrait', length: 917, width: 648 },
  { label: 'C1 Landscape', length: 648, width: 917 },
  { label: 'C2 Portrait', length: 648, width: 458 },
  { label: 'C2 Landscape', length: 458, width: 648 },
  { label: 'C3 Portrait', length: 458, width: 324 },
  { label: 'C3 Landscape', length: 324, width: 458 },
  { label: 'C4 Portrait', length: 324, width: 229 },
  { label: 'C4 Landscape', length: 229, width: 324 },
  { label: 'C5 Portrait', length: 229, width: 162 },
  { label: 'C5 Landscape', length: 162, width: 229 },
  { label: 'C6 Portrait', length: 162, width: 114 },
  { label: 'C6 Landscape', length: 114, width: 162 },
  { label: 'C7 Portrait', length: 114, width: 81 },
  { label: 'C7 Landscape', length: 81, width: 114 },
  { label: 'C8 Portrait', length: 81, width: 57 },
  { label: 'C8 Landscape', length: 57, width: 81 },
  { label: 'C9 Portrait', length: 57, width: 40 },
  { label: 'C9 Landscape', length: 40, width: 57 },
  { label: 'C10 Portrait', length: 40, width: 28 },
  { label: 'C10 Landscape', length: 28, width: 40 },
  { label: 'Letter Portrait', length: 279.4, width: 215.9 },
  { label: 'Letter Landscape', length: 215.9, width: 279.4 },
  { label: 'Legal Portrait', length: 355.6, width: 215.9 },
  { label: 'Legal Landscape', length: 215.9, width: 355.6 },
  { label: 'Tabloid Portrait', length: 431.8, width: 279.4 },
  { label: 'Tabloid Landscape', length: 279.4, width: 431.8 },
  { label: 'Ledger Portrait', length: 279.4, width: 431.8 },
  { label: 'Ledger Landscape', length: 431.8, width: 279.4 },
  { label: 'Executive Portrait', length: 266.7, width: 184.1 },
  { label: 'Executive Landscape', length: 184.1, width: 266.7 },
  { label: 'Folio Portrait', length: 330.2, width: 215.9 },
  { label: 'Folio Landscape', length: 215.9, width: 330.2 },
  { label: 'Quarto Portrait', length: 254, width: 203.2 },
  { label: 'Quarto Landscape', length: 203.2, width: 254 },
  { label: 'Postcard Portrait', length: 148, width: 105 },
  { label: 'Postcard Landscape', length: 105, width: 148 },
  { label: 'Index Card Portrait', length: 127, width: 76.2 },
  { label: 'Index Card Landscape', length: 76.2, width: 127 },
  { label: 'Custom Portrait', length: 0, width: 0 },
  { label: 'Custom Landscape', length: 0, width: 0 },
]
