export const paperTypes = [
  { label: 'Art Card', value: 'art_card' },
  { label: 'Art Paper', value: 'art_paper' },
  { label: 'Board', value: 'board' },
  { label: 'Chromo', value: 'chromo' },
  { label: 'Dalum Recycled', value: 'dalum_recycled' },
  { label: 'Grey Back', value: 'grey_back' },
  { label: 'Gumming Sheet', value: 'gumming_sheet' },
  { label: 'Maplitho A Grade', value: 'maplitho_a_grade' },
  { label: 'Maplitho B Grade', value: 'maplitho_b_grade' },
  { label: 'Maplitho C Grade', value: 'maplitho_c_grade' },
  { label: 'SBS', value: 'sbs' },
  { label: 'Special Fine Paper', value: 'special_fine_paper' },
  { label: 'Superprint', value: 'superprint' },
  { label: 'Whiteback', value: 'whiteback' },
  { label: 'Bond Paper', value: 'bond_paper' },
  { label: 'Coated Paper', value: 'coated_paper' },
  { label: 'Kraft Paper', value: 'kraft_paper' },
  { label: 'Newsprint', value: 'newsprint' },
  { label: 'Offset Paper', value: 'offset_paper' },
  { label: 'Recycled Paper', value: 'recycled_paper' },
  { label: 'Text Paper', value: 'text_paper' },
  { label: 'Vellum', value: 'vellum' },
  { label: 'Wove Paper', value: 'wove_paper' },
  { label: 'Cup Stock', value: 'cup_stock' },
  { label: 'Duplex Board', value: 'duplex_board' },
  { label: 'Folding Box Board', value: 'folding_box_board' },
  { label: 'LWC (Light Weight Coated)', value: 'lwc' },
  { label: 'Sack Kraft Paper', value: 'sack_kraft_paper' },
  { label: 'Solid Bleached Sulphate (SBS)', value: 'solid_bleached_sulphate' },
  { label: 'Virgin Kraft Paper', value: 'virgin_kraft_paper' },
  { label: 'Poster Paper', value: 'poster_paper' },
  { label: 'Thermal Paper', value: 'thermal_paper' },
]

export const paperMakes = [
  { label: 'Prime', value: 'prime' },
  { label: 'Kodak', value: 'kodak' },
  { label: 'Reel Cut', value: 'reel_cut' },
  { label: 'Ruchira', value: 'ruchira' },
  { label: 'Shriyans', value: 'shriyans' },
  { label: 'Others', value: 'others' },
]

export const paperFinishes = [
  { label: 'Glossy', value: 'glossy' },
  { label: 'Matte', value: 'matte' },
  { label: 'Silk', value: 'silk' },
  { label: 'Uncoated', value: 'uncoated' },
  { label: 'Others', value: 'others' },
]
